### ISSUE TITLE
test_vfold0 sacred.utils.NamedConfigNotFoundError: Named config not found: "feed". Available config values are: ()

### ISSUE THREAD

**Issue by viethoang303** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#15]
When I run /examples/test_ssl_abdominal_mri.sh, got this problem: 

test_vfold0 
sacred.utils.NamedConfigNotFoundError: Named config not found: "feed". Available config values are: ()

I think I need to feed the weights of trained model to RELOAD_PATH in examples/test_ssl_abdominal_mri.sh but I still got this error. SO how to fix this???

**Comment by viethoang303** [comment]
I just ran the code and it worked.

In validation.py, I comment line: @ex.automain and run examples/test_ssl_abdominal_mri.sh, it still don't work.
Then I uncomment line: @ex.automain and I can run examples/test_ssl_abdominal_mri.sh again and It worked,

So I don't know why the code work

**Comment by viethoang303** [comment]
The problem is solved so I will close this issues

**Comment by mostafij-rahman** [comment]
How did you solve the issue? What was your value in the RELOAD_PATH?

**Comment by PurmaVishnuVardhanReddy** [comment]
What has to be placed in RELOAD_PATH ? Please clarify....

**Comment by xxxgcat** [comment]
hello，can you share the reload_path? thank you.

**Comment by dengtianheibzzb** [comment]
Sorry, where can I find the path for this' RELOAD_PATH '? I did not see the weight. xx file in the model I trained under './exp'.

**Comment by li-yanling** [comment]
same problem here, could you specify how where is the checkpoint file saved? thanks
