### ISSUE TITLE
About getting the Pseudolabel

### ISSUE THREAD

**Issue by gaowq2017** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#2]
Hi ouyang,
    Good job! I have some problems about getting the pseudolabel as follow:
    1、I can't understand the way of randomly select when from pseudolabel candidates to pseudolabel, according the pixel of pseudolabel candidataes or others?
![image](https://user-images.githubusercontent.com/29697367/93549823-bed3fe00-f99c-11ea-9c90-1b3e5b600903.png)
    2、What's the detail of pseudolabel candidates? How many classes of seudolabel candidates? 400? Each pixel instand of one class?
Thank you very much!  best!

**Comment by cheng-01037** [comment]
Hi, thanks for your interest.

Pseudolabels are stored with label values 0 (background), 1, 2, 3,.... . Different values are used to differentiate each individual pseudolabel.
In each training iteration, a random pseudolabel is selected according to the label value. The task shown to the network is to segment this specific psedulabel label against everything else (i.e., essentially a FG-BG segmentation problem).
Please also see the pseudolabel generation Jupiter notebook for more details.

Cheng

**Comment by cheng-01037** [comment]
@gaowq2017 Hello. May I just kindly ask if you eventually get this code working? Thanks. Please let me know if you have any questions.

**Comment by gaowq2017** [comment]
> @gaowq2017 Hello. May I just kindly ask if you eventually get this code working? Thanks. Please let me know if you have any questions.

Hi ouyang:
    Thank you very much! I can use this code but i use not pseudolabel as the label. Because i don't known how to get the pseudolabel in ourself dataset from superpixels to pseudolabel as follow:
![image](https://user-images.githubusercontent.com/29697367/95280415-83d03680-0887-11eb-876d-31114cd0bf05.png)

**Comment by cheng-01037** [comment]
Thanks for your reply. You can look into `./data/pseudolabel_gen.ipynb` which generates pseudolabel step by step. You might want to change configuration like image paths/ namings according to your own dataset.
