### ISSUE TITLE
AssertionError 

### ISSUE THREAD

**Issue by Sunrise1225** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#21]
![image](https://user-images.githubusercontent.com/77144531/196071106-cc2bcde6-69a0-412c-8685-90dfde7003c0.png)

False appears after the assert statement.I don't know why this happened

Could you please help solve this problem？Thank you.

**Comment by cheng-01037** [comment]
Please check if the term `cls_name` in your training/testing script is set to `grid_proto` (as it is in the example scripts).
