### ISSUE TITLE
when training'/train_ssl_abdominal_ct.sh',an error occurred,KeyError: 'KID_R'

### ISSUE THREAD

**Issue by xxxgcat** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#22]
![1666839926982](https://user-images.githubusercontent.com/95564137/198181464-b408a22d-9c2b-4440-99e0-a5dd178a2323.png)
  if curr_dict["z_id"] in self.tp1_cls_map[self.real_label_name[_ex_cls]][curr_dict["scan_id"]]: # if using setting 1, this slice need to be excluded since it contains label which is supposed to be unseen
**KeyError: 'KID_R'**

**Comment by laiyingxin2** [comment]
same question

**Comment by cheng-01037** [comment]
Can you run the class map generation notebook and see if the problem is still there?
