### ISSUE TITLE
value of the MIN_TP and min_fg_data

### ISSUE THREAD

**Issue by AXu0511** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#24]
May I kindly ask how to set the values of the MIN_TP and min_fg_data in the class_slice_index_gen.ipynb and config_ssl_upload.py respectively while training model on Combined Healthy Abdominal Organ Segmentation dataset MR?

**Comment by cheng-01037** [comment]
These are already provided by the notebook.
