### ISSUE TITLE
Keyerror: 'BG' when testing

### ISSUE THREAD

**Issue by whitenoise-tzx** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#25]
Hi there! Thanks for your great work! I was trying to reproduce your code but encountered the following error:
<img width="1209" alt="截屏2022-11-06 19 11 09" src="https://user-images.githubusercontent.com/72962618/200168094-e53d7368-4d87-40ab-93ea-ba22cca734e5.png">
I followed your preprocess steps accordingly. This confuses me a lot.
I'd be really grateful if you could provide me some suggestions!

**Comment by cheng-01037** [comment]
Please check if you have feed the output file of `[class_slice_index_gen.ipynb](https://github.com/cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation/blob/master/data/CHAOST2/class_slice_index_gen.ipynb)` to the training script

**Comment by you22333** [comment]
same
