### ISSUE TITLE
Testing result using default configs

### ISSUE THREAD

**Issue by tymatfd** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#27]
Hello, thanks for your excellent work. I have something confusing. Are class dice scores in default testing results represent for dice scores   of left/right kidney? It seems to be quite different from results in the paper。

**Comment by tymatfd** [comment]
[[0.88280351 0.74435562]
 [0.83440392 0.80716308]
 [0.82672461 0.78102041]
 [0.81587385 0.77750367]]
INFO - main - mar_val batches classDice: [0.83995147 0.77751069]
INFO - main - mar_val batches meanDice: 0.8087310830351279
INFO - main - mar_val batches classPrec: [0.89149801 0.81449578]
INFO - main - mar_val batches meanPrec: 0.852996898033872
INFO - main - mar_val batches classRec: [0.7999958 0.7510558]
INFO - main - mar_val batches meanRec: 0.7755258011198479

**Comment by tymatfd** [comment]
In paper, it is [73.63 78.39]. I wonder that if i have do any thing wrong

**Comment by cheng-01037** [comment]
You may want to run through all five folds and get the average.
