### ISSUE TITLE
do not know  put the /img and /label folders under ./data/SABS/ directory 

### ISSUE THREAD

**Issue by Lynuluhao** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#29]
Download [Synapse Multi-atlas Abdominal Segmentation dataset](https://www.synapse.org/#!Synapse:syn3193805/wiki/217789) and put the /img and /label folders under ./data/SABS/ directory .
i do not know the /img and /label is in the rawdata or regdata?

**Comment by cheng-01037** [comment]
Sorry but I did not quite get your question ... for downloaded CT these should be nifti files
