### ISSUE TITLE
interm_pred对应的query和GT

### ISSUE THREAD

**Issue by MyFirst905** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#30]
非常感谢您的工作对我的帮助，我运行validation.py后保存在interm_pred的结果找不到对应的原始输入图像，请问这个对应的图像要去哪找呢？

**Comment by cheng-01037** [comment]
These predictions are named as `scan_<id_of_the_image>_label_<label_id>.nii.gz`
