### ISSUE TITLE
Faulty batch detected, skip

### ISSUE THREAD

**Issue by lijing-coder** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#32]
./examples/train_ssl_abdominal_mri.sh 
===================================
train_CHAOST2_Superpix_lbgroup0_scale_MIDDLE_vfold0
INFO - mySSL - Running command 'main'
INFO - mySSL - Started run with ID "9"
INFO - main - ###### Create model ######
###### NETWORK: Using ms-coco initialization ######
INFO - main - ###### Load data ######
INFO - main - ###### Labels excluded in training : [2, 3] ######
INFO - main - ###### Unseen labels evaluated in testing: [2, 3] ######
###### Initial scans loaded: ######
['10', '13', '15', '19', '20', '21', '22', '31', '32', '33', '34', '36', '37', '38', '39']
INFO - main - ###### Set optimizer ######
INFO - main - ###### Training ######
INFO - main - ###### This is epoch 0 of 100 epoches ######
Faulty batch detected, skip
Faulty batch detected, skip
Faulty batch detected, skip
Faulty batch detected, skip
Faulty batch detected, skip
Faulty batch detected, skip
Faulty batch detected, skip
Faulty batch detected, skip
Faulty batch detected, skip
Faulty batch detected, skip

**Comment by cheng-01037** [comment]
Seems that the data has not been corrected loaded...

**Comment by feelingsa** [comment]
Hello, I also encountered the same problem, may I ask if you have solved it? I checked that the trainloader loaded the correct data.
