### ISSUE TITLE
Some files needed do NOT exist

### ISSUE THREAD

**Issue by YOU-95z** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#33]
![image](https://user-images.githubusercontent.com/114045085/233983392-5f0a4073-fbef-4cbe-95be-e0ed81d1ca7e.png)
I have finished all the pre-processs for data, but when training, issues shown in the screen-shot occured.

**Comment by cheng-01037** [comment]
It looks like you did not run [pseudo label generation](https://github.com/cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation/blob/master/data/pseudolabel_gen.ipynb) for CHAOS dataset.
