### ISSUE TITLE
Synapse_abdominal_classmap.ipynb incorrect n_slice

### ISSUE THREAD

**Issue by levayz** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#35]
niftiio has no attribute read_nii_image so running lb = nio.read_nii_image(segs[0])  for example fails, should be changed to nio.read_nii_bysitk.
Also when reading an image with read_nii_bysitk, the Z dimension comes first. The notebook  currently has:
n_slice = lb_vol.shape[-1]
which takes the number of "y" pixels in the slice (which is 256), should change to 
n_slice = lb_vol.shape[0]

**Comment by cheng-01037** [comment]
Thank you so much for reminding. Now updated with `read_nii_bysitk` and the notebook should be executable.

Sorry for the confusion as inconsistent loading functions are used. The original `read_nii_image` uses `nibabel` for reading instead, which moves z axis to the last dimension. It goes like this:
```python
import nibabel; read_nii_image = lambda x: nibabel.load(x).get_data()
```
