### ISSUE TITLE
RELOAD_PATH

### ISSUE THREAD

**Issue by jinst2022** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#36]
When I run /examples/test_ssl_abdominal_mri.sh, got this problem:

test_vfold0
sacred.utils.NamedConfigNotFoundError: Named config not found: "feed". Available config values are: ()

I think I need to feed the weights of trained model to RELOAD_PATH in examples/test_ssl_abdominal_mri.sh , where can I find the path for this' RELOAD_PATH '?

**Comment by levayz** [comment]
should be line 49 in the testing script (examples/test_ssl_abdominal_mri.sh)

**Comment by cheng-01037** [comment]
This should be the path for the model checkpoints
