### ISSUE TITLE
There was an issue testing CMR data with this code

### ISSUE THREAD

**Issue by dengtianheibzzb** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#42]
I will use the code on the CMR dataset, and during the training phase, the loss can decrease normally. However, during the testing phase, there are several of the tested categories that were all empty
@cheng-01037 
![9L%N3)$IOQ4% %SFI4GOO%O](https://github.com/cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation/assets/91410692/f9fb6078-b344-4f9e-bdbe-5523a842fc2d)

**Comment by WangBingJian233** [comment]
> 我将使用 CMR 数据集上的代码，在训练阶段，损失可以正常减少。但是，在测试阶段，有几个测试的类别都是空的 ![9L%N3)$IOQ4% %SFI4GOO%O](https://private-user-images.githubusercontent.com/91410692/296418640-f9fb6078-b344-4f9e-bdbe-5523a842fc2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTgwNjUsIm5iZiI6MTcyOTQ5Nzc2NSwicGF0aCI6Ii85MTQxMDY5Mi8yOTY0MTg2NDAtZjlmYjYwNzgtYjM0NC00ZjllLWJkYmUtNTUyM2E4NDJmYzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDA4MDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMTBlYTdjMDdiZmRiNjM4ZmIyODAxMmQ5NTlkMDE4MzIyMzRmN2E0Y2U2NjIzNDE3NDA5ODRmMjIxYWYzYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OlLlLCsf4qXVGL_IM_GRx-GeaKTpLxkN20E9RrZJEQc)

Hello, could you please give me a copy of the CMR data set? Pre-processing before or after data is fine. Thank you very much!
