### ISSUE TITLE
Self-supervised-Fewshot-Medical-Image-Segmentation AssertionError error image and label

### ISSUE THREAD

**Issue by rp775** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#5]
Hi CHENG

thanks for sharing the code. I am trying to run the code to see the results.

I followed the same steps that you explained on the GitHub.

but getting the error when I am trying to run the validation code.[Trying code was fine and i see the model snapshot created]
I haven't changed anything. I just downloaded the Abdominal MRI dataset and did preprocess as you explained.

I am getting an issue with this line. Not sure what I am missing. please throw some light on this.

  te_dataset, te_parent = med_fewshot_val(
        dataset_name = baseset_name,
        base_dir=_config['path'][baseset_name]['data_dir'],
        idx_split = _config['eval_fold'],
        scan_per_load = _config['scan_per_load'],
        act_labels=test_labels,
        npart = _config['task']['npart'],
        nsup = _config['task']['n_shots'],
        extern_normalize_func = norm_func
    )

./examples/test_ssl_abdominal_mri.sh 

===================================

test_vfold0

---------1

WARNING - root - Changed type of config entry "min_fg_data" from str to int

INFO - mySSL - Running command 'main'

INFO - mySSL - Started run with ID "7"

<bound method Ingredient.config of <sacred.experiment.Experiment object at 0x7fce0880d910>>

INFO - main - ###### Reload model pretrained_model/checkpoints/50000.pth ######

###### Pre-trained model fpretrained_model/checkpoints/50000.pth has been loaded ######

INFO - main - ###### Load data ######

INFO - main - ###### Labels excluded in training : [2,3] ######

INFO - main - ###### Unseen labels evaluated in testing: [2, 3] ######

<here i printed all value that i am passing>

baseset_name- CHAOST2
_config['path'][baseset_name]['data_dir']- ./data/CHAOST2/chaos_MR_T2_normalized/

_config['eval_fold'] - 0

_config['scan_per_load']-  -1

test_labels- {2, 3}

_config['task']['npart'] - 3

_config['task']['n_shots']- 1

------------------

val

0

------------------

slice(0, 5, None)

------------------

0

------------------

1

------------------

2

------------------

3

------------------

4

['1', '2', '10', '11', '12']

###### Dataset: using external normalization statistics ######

1

----------itm-------

./data/CHAOST2/chaos_MR_T2_normalized/image_1.nii

./data/CHAOST2/chaos_MR_T2_normalized/image_1.nii

------------------

{'spacing': (1.25, 1.25, 7.699999809265137), 'origin': (-192.6536865234375, 200.66128540039062, -77.0921630859375), 'direction': (1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0), 'array_size': (36, 256, 256)}

./data/CHAOST2/chaos_MR_T2_normalized/label_1.nii

------------------

image----------------

36

---------label----------

36

2

----------itm-------

<on this image both label and image array size matched but but for next image it is not matched. do i need to reprocess the image again or can i skip this image from testing>

./data/CHAOST2/chaos_MR_T2_normalized/image_2.nii

./data/CHAOST2/chaos_MR_T2_normalized/image_2.nii

iiiiiiiiiiiiiiiiiiiii

{'spacing': (1.25, 1.25, 7.699999809265137), 'origin': (-200.404296875, 181.1779327392578, -50.865966796875), 'direction': (0.9999885559243149, 0.0, 0.004784142800534769, 0.0, -1.0, 0.0, -0.00478414259858687, 0.0, 0.9999885559233486), 'array_size': (31, 256, 256)}

./data/CHAOST2/chaos_MR_T2_normalized/label_2.nii

iiiiiiiiiiiiiiiiiiiii

image----------------

31

-----label--------------

46

ERROR - mySSL - Failed after 0:00:06!

Traceback (most recent calls WITHOUT Sacred internals):

  File "validation.py", line 119, in main

    extern_normalize_func = norm_func

  File "/data/raj/shot/Self-supervised-Fewshot-Medical-Image-Segmentation/dataloaders/dev_customized_med.py", line 245, in med_fewshot_val

    mydataset = ManualAnnoDataset(which_dataset = dataset_name, base_dir=base_dir, idx_split = idx_split, mode = 'val', scan_per_load = scan_per_load, transforms=None, min_fg = 1, fix_length = fix_length, nsup = nsup, **kwargs)

  File "/data/raj/shot/Self-supervised-Fewshot-Medical-Image-Segmentation/dataloaders/ManualAnnoDatasetv2.py", line 86, in __init__

    self.actual_dataset = self.read_dataset()

  File "/data/raj/shot/Self-supervised-Fewshot-Medical-Image-Segmentation/dataloaders/ManualAnnoDatasetv2.py", line 179, in read_dataset

    assert img.shape[-1] == lb.shape[-1]

AssertionError

---------2

**Comment by Goooo1898** [comment]
> ssertionError

can you solve this problem ?

**Comment by Cmnotjx** [comment]
> > ssertionError
> 
> can you solve this problem ?

![2022-06-11 20-42-32 的屏幕截图](https://user-images.githubusercontent.com/91420273/173188818-25cb9a02-9a2c-42ec-a688-915487ea5280.png)
Have you experienced this problem when dealing with CT datasets? KID_R and KID_l are empty on my Classmap.json

**Comment by cheng-01037** [comment]
You probably want to run [this](https://github.com/cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation/blob/master/data/CHAOST2/class_slice_index_gen.ipynb) for CT as well.
