### ISSUE TITLE
Can you share the config file for test run? This repository does not have the config file for testing.

### ISSUE THREAD

**Issue by pongopal** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#7]
Can you share the config file for test run? This repository does not have the config file for testing.

**Comment by cheng-01037** [comment]
The testing scripts should automatically override the default options in [config_ssl_upload.py](https://github.com/cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation/blob/master/config_ssl_upload.py)
