### ISSUE TITLE
Card-MRI DataSet

### ISSUE THREAD

**Issue by EyesUXiao** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#8]
Hello, may I ask, how to obtain the data set of Cardiac MRI？

**Comment by SakurajimaMaiii** [comment]
> 

I think Cardicac dataset is from http://www.sdspeople.fudan.edu.cn/zhuangxiahai/0/mscmrseg19/data.html.

**Comment by EyesUXiao** [comment]
> > 
> 
> I think Cardicac dataset is from http://www.sdspeople.fudan.edu.cn/zhuangxiahai/0/mscmrseg19/data.html.

Thank you very much!

**Comment by WangBingJian233** [comment]
Hello, now the Cardicac dataset is not available, could you please give us the Cardicac dataset? Thank you very much

**Comment by WangBingJian233** [comment]
> > 
> 
> 我认为 Cardicac 数据集来自 http://www.sdspeople.fudan.edu.cn/zhuangxiahai/0/mscmrseg19/data.html。

Hello, now the Cardicac dataset is not available, could you please give us the Cardicac dataset? Thank you very much！
