### ISSUE TITLE
How to set up to train only manual annotation data

### ISSUE THREAD

**Issue by DpDark** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#9]
Only SSL training is given in the code. How to set it to only train manual annotation data？

**Comment by xzxedu** [comment]
Hi did you successfully train on the manual annotation data? Besides, may I ask how do you deal with transforms=None on the validation.py dataset, as on ManualAnnoDataset I notice it only has "img, lb = self.transforms()" which might get error if transforms is None.

**Comment by Cmnotjx** [comment]
> Only SSL training is given in the code. How to set it to only train manual annotation data？
![2022-06-11 20-42-32 的屏幕截图](https://user-images.githubusercontent.com/91420273/173188886-feb38e7a-7299-46d4-af72-bd6fc45d87c9.png)

Have you experienced this problem when dealing with CT datasets? KID_R and KID_l are empty on my Classmap.json

**Comment by cheng-01037** [comment]
Thanks for the question and sorry for the late response. Will update in a future version.

**Comment by PurmaVishnuVardhanReddy** [comment]
> Only SSL training is given in the code. How to set it to only train manual annotation data？

Could you please elaborate on this ?

**Comment by cheng-01037** [comment]
Hi yes will update the code to support manual annotation training but I am afraid that I may not have time to clean up the code in recent days ... sorry about that.

 The core idea is still to alleviate over-fitting and to make sure prototype alignment loss not to explode.

**Comment by CYF2000127** [comment]
> Hi yes will update the code to support manual annotation training but I am afraid that I may not have time to clean up the code in recent days ... sorry about that.
> 
> The core idea is still to alleviate over-fitting and to make sure prototype alignment loss not to explode.

Hi,  I also what to ask how to set it to only train manual annotation data？Is the code avalible?
